openapi: 3.0.3
info:
  title: "Quality Management API"
  version: "1.0.0"

servers:
  - url: https://doi6w9idtk.execute-api.us-west-2.amazonaws.com/Prod
    description: Prod API Gateway Endpoint


paths:
  /campaign:
    $ref: './campaigns/createCampaign.yaml'